/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

import admin_screen.AdminMainScreen;
import java.sql.Timestamp;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.dao.LoginInfoDao;
import model.to.LoginInfoTo;
import user_screen.UserMainScreen;
import utility.ErrorHandler;
import utility.Validations;

/**
 *
 * @author sushant saini
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        try
        {
            ImageIcon icon;
            icon= new ImageIcon(getClass().getResource("/icons/movie-box-icon.png"));
            setIconImage(icon.getImage()); 
        }catch(Exception ex)
        { 
            ErrorHandler.showStackTrace(ex);
        }

        initComponents();
        setLocationRelativeTo(null);
        getRootPane().setDefaultButton(btnlogin);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfusername1 = new javax.swing.JTextField();
        jpfpassword = new javax.swing.JPasswordField();
        btnlogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Screen");
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Enter User Name:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Enter Password:");

        jtfusername1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jpfpassword.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        btnlogin.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        btnlogin.setText("Login");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfusername1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                    .addComponent(jpfpassword))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(btnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfusername1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpfpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
       String username=jtfusername1.getText().trim();
       String password=new String(jpfpassword.getPassword());
       String message="";
       if(Validations.isEmpty(username)||Validations.isEmpty(password))
           message="Pleasse Give All Details";
       else {
           LoginInfoDao action=new LoginInfoDao();
           LoginInfoTo record=action.getRecord(username);
           if(record!=null){
               if(record.getPassword().equals(password)){
                   if(record.getRolename().equalsIgnoreCase("admin"))
                   { 
                       
                       AdminMainScreen ams=new AdminMainScreen(username);
                       ams.setVisible(true);
                       if(record.getLastlogin()==null){
                           message="Welocme "+username.toUpperCase()+" For First Time";
                       }else{
                           message="Welocme "+username.toUpperCase()+" Your Last Visit : "+record.getLastlogin();
                       }
                           record.setLastlogin(new Timestamp(System.currentTimeMillis()));
                           action.updateRecord(record);
                       dispose();
                   }else if(record.getRolename().equals("user")){
                       
                       UserMainScreen ums=new UserMainScreen(username); 
                       ums.setVisible(true);
                       if(record.getLastlogin()==null){
                           message="Welocme "+username.toUpperCase()+" For First Time";
                       }else{
                           message="Welocme "+username.toUpperCase()+" Your Last Visit : "+record.getLastlogin();
                       } record.setLastlogin(new Timestamp(System.currentTimeMillis()));
                           action.updateRecord(record);
                       dispose(); 
                   }else{
                       message="Insufficient Privileges";
                   }
               }
               else{
                    message="Invalid Username And Password";
               }
                   
           }
               
           else{
                   message="Invalid Username And Password";
                   }
       }
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jpfpassword;
    private javax.swing.JTextField jtfusername1;
    // End of variables declaration//GEN-END:variables
}
