/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin_screen;

import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import model.dao.ScreenInfoDao;
import model.dao.ScreenTicketsDao;
import model.dao.TicketTypeDao;
import model.to.ScreenInfoTo;
import model.to.ScreenTicketsTo;
import model.to.TicketTypeTo;
import utility.Operation;
import utility.Validations;

/**
 *
 * @author sushant saini
 */
public class AddNewScreenTickets extends javax.swing.JInternalFrame {
    private List<ScreenInfoTo> screens;
    private List<TicketTypeTo> tickets ;
    private int stid;
    /**
     * Creates new form AddNewScreenTickets
     */
    public AddNewScreenTickets() {
        initComponents();
        bindScreenCombo();
        
    }
    public AddNewScreenTickets(int stid) {
        this();
        ScreenTicketsTo record = new ScreenTicketsDao().getRecord(stid);
        if (record != null) {
            this.stid = stid;
            setTitle("Edit Screen Tickets Details");
            btnoperation.setText("Update Screen Tickets Details");
            jtfseatinrow.setText(String.valueOf(record.getSeatinrow()));
            jtftotalrow.setText(String.valueOf(record.getTotalrow()));
            for (int index = 1; index < jcbscreenid.getItemCount(); index++) {
                ScreenInfoTo ct = (ScreenInfoTo) jcbscreenid.getItemAt(index);
                if (ct.getScreenid().equals(record.getScreenid())) {
                    jcbscreenid.setSelectedIndex(index);
                    break;
                }   
            }
            for(int index = 1; index < jcbtickettypeid.getItemCount(); index++){
                TicketTypeTo ttt = (TicketTypeTo) jcbtickettypeid.getItemAt(index);
                if(ttt.getTypeid() == record.getTypeid()){
                    jcbtickettypeid.setSelectedIndex(index);
                    break;
                }
            }
                    
               
            
        }
    }

   
    private void bindScreenCombo(){
        jcbscreenid.removeAllItems();
        jcbscreenid.addItem("Choose Screen");
        screens=new ScreenInfoDao().getAllRecord();
        if(screens!=null&&screens.size()>0){
            for(ScreenInfoTo sc:screens){
                jcbscreenid.addItem(sc);
            }
        }
            
    }
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcbtickettypeid = new javax.swing.JComboBox<>();
        jcbscreenid = new javax.swing.JComboBox<>();
        btnoperation = new javax.swing.JButton();
        jtftotalrow = new controls.IntegerTextField();
        jtfseatinrow = new controls.IntegerTextField();

        setClosable(true);
        setIconifiable(true);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Choose Ticket Type:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Enter No. Of Seat In Row");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Choose Screen:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Enter Total No. Of Rows:");

        jcbtickettypeid.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jcbtickettypeid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcbscreenid.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jcbscreenid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbscreenid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbscreenidItemStateChanged(evt);
            }
        });
        jcbscreenid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbscreenidActionPerformed(evt);
            }
        });

        btnoperation.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        btnoperation.setText("Add Screen Tickets");
        btnoperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoperationActionPerformed(evt);
            }
        });

        jtftotalrow.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jtfseatinrow.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(122, 122, 122)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(70, 70, 70)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbtickettypeid, javax.swing.GroupLayout.Alignment.TRAILING, 0, 289, Short.MAX_VALUE)
                            .addComponent(jcbscreenid, javax.swing.GroupLayout.Alignment.TRAILING, 0, 289, Short.MAX_VALUE)
                            .addComponent(jtftotalrow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfseatinrow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(112, 112, 112))
                    .addComponent(jLabel4)))
            .addGroup(layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(btnoperation, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbscreenid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbtickettypeid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtftotalrow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfseatinrow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnoperation, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbscreenidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbscreenidActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jcbscreenidActionPerformed

    private void btnoperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoperationActionPerformed
        // TODO add your handling code here:
        String totalrow1=jtftotalrow.getText().trim();
        String seatinrow1=jtfseatinrow.getText().trim();
        String message="";
        boolean allvalid=true;
        if(jcbscreenid.getSelectedIndex()==0||jcbtickettypeid.getSelectedIndex()==0)
        { allvalid=false;
        if(jcbscreenid.getSelectedIndex()==0)
            message="Please Choose Any Screen";
        else
            message="Please Choose Any Ticket ";
        }
        else if(Validations.isEmpty(totalrow1)||Validations.isEmpty(seatinrow1)){
            message="Please Give All Details";
            allvalid=false;
        }
        else if(!(Validations.isFloat(totalrow1)&&Validations.isFloat(seatinrow1))){
            message="Please Enter Valid number";
            allvalid=false;
        }
       
        if(allvalid){
            int totalrow=Integer.parseInt(totalrow1);
            int seatinrow=Integer.parseInt(seatinrow1);
            TicketTypeTo tt=(TicketTypeTo) jcbtickettypeid.getSelectedItem();
            ScreenInfoTo si= (ScreenInfoTo) jcbscreenid.getSelectedItem();
            ScreenTicketsTo  record=new ScreenTicketsTo();
            record.setScreenid(si.getScreenid());
            record.setTypeid(tt.getTypeid());
            record.setTotalrow(totalrow);
            record.setSeatinrow(seatinrow);
            ScreenTicketsDao action= new ScreenTicketsDao();
            if(btnoperation.getText().contains("Add")){
            if(action.insertRecord(record)){
                message="New Screen Tickets Added";
                JInternalFrame[] frames=getDesktopPane().getAllFrames();
                    if(frames!=null && frames.length>1){
                        for(JInternalFrame frame:frames){
                            if(frame instanceof ViewScreenTicketsDetails){
                               ((ViewScreenTicketsDetails)frame).bindTableScreenTickets();
                            }
                        }
                    }
                bindScreenCombo();
            }else{
                message="Failure due to "+action.getError_message();
            }
            }else if(btnoperation.getText().contains("Update")){
                record.setStid(stid);
                if(action.updateRecord(record)){
                message="Screen Tickets Updated";
                bindScreenCombo();
            }else{
                message="Failure due to "+action.getError_message();
            }
                ViewScreenDetails vsd=new ViewScreenDetails();
                 Operation.openInternalFrame(getDesktopPane(), vsd);
                dispose();
            }
        }
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnoperationActionPerformed

    private void jcbscreenidItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbscreenidItemStateChanged
        // TODO add your handling code here:
        jcbtickettypeid.removeAllItems();
        jcbtickettypeid.addItem("Choose ticket");
        if(jcbscreenid.getSelectedIndex()>0){
            ScreenInfoTo sc=(ScreenInfoTo) jcbscreenid.getSelectedItem();
            if(btnoperation.getText().contains("Add")){
            List<TicketTypeTo> tickets=new TicketTypeDao().getAllRecord(sc.getScreenid());
            if(tickets!=null&&tickets.size()>0){
                for(TicketTypeTo tc:tickets){
                    jcbtickettypeid.addItem(tc); 
                }
            }
            }else{
                List<TicketTypeTo> tickets=new TicketTypeDao().getAllRecord1(sc.getScreenid());
            if(tickets!=null&&tickets.size()>0){
                for(TicketTypeTo tc:tickets){
                    jcbtickettypeid.addItem(tc); 
                }
            }
            }
        }
    }//GEN-LAST:event_jcbscreenidItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnoperation;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<java.lang.Object> jcbscreenid;
    private javax.swing.JComboBox<java.lang.Object> jcbtickettypeid;
    private controls.IntegerTextField jtfseatinrow;
    private controls.IntegerTextField jtftotalrow;
    // End of variables declaration//GEN-END:variables
}
