/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin_screen;

import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import model.dao.TicketTypeDao;
import model.to.ScreenInfoTo;
import model.to.TicketTypeTo;
import utility.Operation;
import utility.Validations;

/**
 *
 * @author sushant saini
 */
public class AddNewTicket extends javax.swing.JInternalFrame {
private int typeid;
    /**
     * Creates new form AddNewTicket
     */
    public AddNewTicket() {
        initComponents();
    }
 public AddNewTicket(TicketTypeTo record){
        this();
        if(record!=null){
            this.typeid=record.getTypeid();
            jtftypename.setText(record.getTypename());
            jtfprice.setText( String.valueOf(record.getPrice()));
            btnoperation.setText("Update Ticket Details");
            setTitle("Edit Ticket Details ");
            jtftypename.setEditable(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtftypename = new javax.swing.JTextField();
        btnoperation = new javax.swing.JButton();
        jtfprice = new controls.FloatTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add New Ticket");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Enter Ticket Type:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Enter Price:");

        jtftypename.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        btnoperation.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        btnoperation.setText("Add New Ticket");
        btnoperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoperationActionPerformed(evt);
            }
        });

        jtfprice.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtftypename, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                            .addComponent(jtfprice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(btnoperation, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtftypename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfprice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(btnoperation, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnoperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoperationActionPerformed
        // TODO add your handling code here:
        String typename=jtftypename.getText().trim();
        String price1=jtfprice.getText().trim();
        String message="";
        boolean allvalid=true;
        if(Validations.isEmpty(typename)||Validations.isEmpty(price1)){
            message="Please Give All Details";
            allvalid=false;
        }
        else if(!Validations.isFloat(price1)){
            message="Please Enter Valid Price";
            allvalid=false;
        }
        else if(!Validations.isLetterAndSpace(typename)){
            message="Please Enter Letter In Ticket Type";
            allvalid=false;
        }
        if(allvalid){
            float price=Float.parseFloat(price1);
            TicketTypeTo  record=new TicketTypeTo();
            record.setTypename(typename);
            record.setPrice(price);
            TicketTypeDao action= new TicketTypeDao();
            if(btnoperation.getText().contains("Add")){
            if(action.insertRecord(record)){
                message="New Ticket Added";
                JInternalFrame[] frames=getDesktopPane().getAllFrames();
                    if(frames!=null && frames.length>1){
                        for(JInternalFrame frame:frames){
                            if(frame instanceof ViewTicketDetails){
                               ((ViewTicketDetails)frame).bindTableTicket();
                            }
                        }
                    }
            }else{
                message="Failure due to "+action.getError_message();
            }
            }else if(btnoperation.getText().contains("Update")){
                record.setTypeid(typeid);
              if(action.updateRecord(record)){
                 message=" Ticket Updated";
             }else{
                 message="Failure due to "+action.getError_message();
             }
              ViewTicketDetails vcd=new ViewTicketDetails();
                 Operation.openInternalFrame(getDesktopPane(), vcd);
                 dispose();
             }else{
                 message="Invalid Operation";
             }
        }
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnoperationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnoperation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private controls.FloatTextField jtfprice;
    private javax.swing.JTextField jtftypename;
    // End of variables declaration//GEN-END:variables
}
