/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin_screen;

import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import model.dao.ScreenInfoDao;
import model.to.ScreenInfoTo;
import utility.Operation;
import utility.Validations;


/**
 *
 * @author sushant saini
 */
public class AddNewScreen extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddNewScreen
     */
    public AddNewScreen() {
        initComponents();
    }
    public AddNewScreen(ScreenInfoTo record){
        this();
        if(record!=null){
            jtfscreenid.setText(record.getScreenid());
            jtfscreenname.setText(record.getScreenname());
            btnoperation.setText("Update Screen Details");
            setTitle("Edit Screen Details ");
            jtfscreenid.setEditable(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfscreenname = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jtfscreenid = new javax.swing.JTextField();
        btnoperation = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Add New Screen Details");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Enter Screen Name:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Enter Screen Id :");

        jtfscreenname.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jtfscreenname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfscreennameActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jtfscreenid.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        btnoperation.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        btnoperation.setText("Add New Screen");
        btnoperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoperationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(btnoperation, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(jtfscreenname, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(422, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(42, 42, 42)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(422, Short.MAX_VALUE)
                    .addComponent(jtfscreenid, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(42, 42, 42)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfscreenname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btnoperation, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(120, 120, 120)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(301, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(86, 86, 86)
                    .addComponent(jtfscreenid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(301, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnoperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoperationActionPerformed
        // TODO add your handling code here:
        String screenid=jtfscreenid.getText().trim();
        String screenname=jtfscreenname.getText().trim();
         String message="";
         if(Validations.isEmpty(screenid)||Validations.isEmpty(screenname)){
             message="Please Give All Details";
         }
         else {
             ScreenInfoTo  record=new ScreenInfoTo();
             record.setScreenid(screenid);
             record.setScreenname(screenname);
             ScreenInfoDao action= new ScreenInfoDao();
             if(btnoperation.getText().contains("Add")){
             if(action.insertRecord(record)){
                 message="New Screen Added";
                 JInternalFrame[] frames=getDesktopPane().getAllFrames();
                    if(frames!=null && frames.length>1){
                        for(JInternalFrame frame:frames){
                            if(frame instanceof ViewScreenDetails){
                               ((ViewScreenDetails)frame).bindTableScreen();
                            }
                        }
                    }
             }else{
                 message="Failure due to "+action.getError_message();
             }  
             }else if(btnoperation.getText().contains("Update")){
              if(action.updateRecord(record)){
                 message=" Screen Updated";
             }else{
                 message="Failure due to "+action.getError_message();
             }
              ViewScreenDetails vcd=new ViewScreenDetails();
                 Operation.openInternalFrame(getDesktopPane(), vcd);
                 dispose();
             }else{
                 message="Invalid Operation";
             }
           }
         JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnoperationActionPerformed

    private void jtfscreennameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfscreennameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfscreennameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnoperation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jtfscreenid;
    private javax.swing.JTextField jtfscreenname;
    // End of variables declaration//GEN-END:variables
}
