/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin_screen;

import java.awt.image.BufferedImage;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import model.dao.MovieInfoDao;
import model.dao.MovieTimingDao;
import model.dao.SaleDetailsDao;
import model.dao.ScreenInfoDao;
import model.dao.TicketSaleDao;
import model.dao.TicketTypeDao;
import model.to.MovieInfoTo;
import model.to.MovieTimingTo;
import model.to.SaleDetailsTo;
import model.to.ScreenInfoTo;
import model.to.TicketSaleTo;
import model.to.TicketTypeTo;

/**
 *
 * @author sushant saini
 */
public class ViewBookingDetails extends javax.swing.JInternalFrame {
private List<TicketSaleTo> movies;
    /**
     * Creates new form ViewBookingDetails
     */
    public ViewBookingDetails() {
        initComponents();
        bindTableBooking();
    }
    void bindTableBooking(){
         String[] col_names={"S.No.","Movie Name","Show date","Time","Screen","Seat No.","Price"};
        Object[][]  records=null;
        movies=new TicketSaleDao().getAllRecord();
        
        if(movies!=null&&movies.size()>0){
            int count=0;
            
            int index=0;    
              for(TicketSaleTo s:movies){
              count=count+s.getTotalseat();}
               records=new Object[count][col_names.length];
            for(TicketSaleTo sc:movies){
            int mtid=sc.getMtid();
            MovieTimingTo time=new MovieTimingDao().getRecord(mtid);
            MovieInfoTo name=new MovieInfoDao().getRecord(time.getMovieid());
                ScreenInfoTo sname=new ScreenInfoDao().getRecord(time.getScreenid());
               
            List<SaleDetailsTo> sale=new SaleDetailsDao().getAllRecord(sc.getSaleid());
           
          
                for(SaleDetailsTo sc1:sale){
                TicketTypeTo tname=new TicketTypeDao().getRecord(sc1.getTypeid());     
            records[index]=new  Object[]{index+1,name.getMoviename(),sc.getShowdate(),time.getStarttime(),sname.getScreenname(),sc1.getSeatno(),sc1.getPrice()};
              index++;  }
            
            }
        }else{
            records=new Object[1][col_names.length];
            records[0]=new  Object[]{"No Information","No Information","No Information","No Information","No Information","No Information","No Information","No Information","No Information"};
        }
        DefaultTableModel model = new DefaultTableModel(records, col_names) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if(columnIndex == 7){
                    return ImageIcon.class;
                }
                return super.getColumnClass(columnIndex); 
            }
            
        };
        tablebooking.getTableHeader().setReorderingAllowed(false);
        tablebooking.setAutoCreateRowSorter(true);
        
        tablebooking.setModel(model);
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablebooking = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("ViEW BOOKING DETAILS");

        tablebooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablebooking);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablebooking;
    // End of variables declaration//GEN-END:variables
}
